### ISSUE TITLE
Importing OpenMC causes a seg fault

### ISSUE THREAD

**Issue by abachma2** [arfc/openmcyclus#12]
Including ``import openmc`` in the archetype file causes a seg fault (sometimes SIGSEGV, sometimes SEGABRT) after the simulation runs and writes the results to the output database. 

A common message with the segmentation fault is: ``double-linked list``, and the traceback to different parts of python. After doing some mild debugging with gdb, I have concluded that python is trying to access memory that it is not supposed to. 

A traceback using gdb:
``Program received signal SIGSEGV, Segmentation fault.
0x00007ffff3cf6fd0 in _int_free () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install glibc-2.17-326.el7_9.x86_64
(gdb) where
#0  0x00007ffff3cf6fd0 in _int_free () from /lib64/libc.so.6
#1  0x00007fffa0a1f0ad in pybind11::cpp_function::initialize_generic(std::unique_ptr<pybind11::detail::function_record, pybind11::cpp_function::InitializingFunctionRecordDeleter>&&, char const*, std::type_info const* const*, unsigned long)::{lambda(void*)#1}::_FUN(void*)
    ()
   from /home/abachmann/anaconda3/envs/cyctest-4/lib/python3.10/site-packages/scipy/fft/_pocketfft/pypocketfft.cpython-310-x86_64-linux-gnu.so
#2  0x00007fffa0a2a4bb in _ZZN8pybind117capsuleC4EPKvPFvPvEENUlP7_objectE_4_FUNES7_ ()
   from /home/abachmann/anaconda3/envs/cyctest-4/lib/python3.10/site-packages/scipy/fft/_pocketfft/pypocketfft.cpython-310-x86_64-linux-gnu.so
#3  0x00007fffed6d6169 in capsule_dealloc ()
   from /home/abachmann/anaconda3/envs/cyctest-4/lib/libpython3.10.so.1.0
#4  0x00007fffed60c857 in meth_dealloc ()
   from /home/abachmann/anaconda3/envs/cyctest-4/lib/libpython3.10.so.1.0
#5  0x00007fffed5ff55a in tupledealloc ()
   from /home/abachmann/anaconda3/envs/cyctest-4/lib/libpython3.10.so.1.0
#6  0x00007fffed6e582d in partial_clear ()
   from /home/abachmann/anaconda3/envs/cyctest-4/lib/libpython3.10.so.1.0
#7  0x00007fffed5f6855 in gc_collect_main ()
   from /home/abachmann/anaconda3/envs/cyctest-4/lib/libpython3.10.so.1.0
#8  0x00007fffed6e0a0c in _PyGC_CollectNoFail.isra.0 ()
   from /home/abachmann/anaconda3/envs/cyctest-4/lib/libpython3.10.so.1.0
#9  0x00007fffed6df4e4 in Py_FinalizeEx.localalias ()
   from /home/abachmann/anaconda3/envs/cyctest-4/lib/libpython3.10.so.1.0
#10 0x00007ffff3cafce9 in __run_exit_handlers () from /lib64/libc.so.6
#11 0x00007ffff3cafd37 in exit () from /lib64/libc.so.6
#12 0x00007ffff3c9855c in __libc_start_main () from /lib64/libc.so.6
#13 0x00005555555636e9 in _start ()
``

**Comment by samgdotson** [comment]
Have you seen this [post](https://stackoverflow.com/questions/10035541/what-causes-a-python-segmentation-fault)? Maybe it will help, or at least offer a way for a better traceback.

**Comment by nsryan2** [comment]
In #22 there were changes to the depletion step that would warrant updates to these tests. Per the discussion there, these updates will come with the PR that addresses this issue.
